name: Mega evil Pavel's action
description: Boo!

inputs:
  message-prefix:
    description: Prefix
    required: true

runs:
  using: composite
  steps:
    - name: csha
      shell: bash
      id: csha
      env:
        INP_M_PRFX: ${{ inputs.message-prefix }}
      run: |
        sha=$(git log -1 --pretty=format:"%h")
        echo "Short sha for $INP_M_PRFX: $sha"
        echo "s=$sha" >> $GITHUB_OUTPUT

    - shell: bash
      name: msha
      id: msha
      run: |
        message=$(git log -1 --pretty=format:"%B")
        echo "Last commit message: $message"
        echo "m=$message" >> $GITHUB_OUTPUT
outputs:
  short-sha:
    description: short sha
    value: ${{ steps.csha.outputs.s }}
  commit-message:
    description: msg
    value: ${{ steps.msha.outputs.m }}